app/__init__.py
# -*- coding: utf-8 -*-
from flask import Flask, request, session, render_template, flash, abort
import importlib


def create_app():
    """Create an application."""
    app = Flask(__name__)
    app.config.from_object('app.settings')
    load_modules(app)
    return app


def load_modules(app):
    # start page
    from app.views.main import mod as main_blueprint

    app.register_blueprint(main_blueprint)

    # load and register enabled modules
    for mod_name in app.config['ENABLED_MODULES']:
        module = importlib.import_module('app.views.' + mod_name)
        app.register_blueprint(module.mod, url_prefix='/' + mod_name)


app = create_app()

app/views/main.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template

mod = Blueprint('main', __name__)


@mod.route('/')
def index():
    return render_template('index.html')

app/views/system.py
# -*- coding: utf-8 -*-
import json
import os
import subprocess
import psutil
from datetime import datetime
from flask import Blueprint, jsonify

mod = Blueprint('system', __name__)


@mod.route('/info')
def get_system_info():
    uptime = datetime.now() - datetime.fromtimestamp(psutil.boot_time())
    temp = os.popen('vcgencmd measure_temp').readline().replace("temp=", "").replace('\'C\n', '')
    mem = psutil.virtual_memory()
    net = psutil.net_io_counters()
    swap = psutil.swap_memory()
    disk = psutil.disk_partitions()

    info = {'uptime': str(uptime).split('.')[0],
            'load': os.getloadavg(),
            'temp': temp,
            'net': {'recv': net.bytes_recv,
                    'sent': net.bytes_sent},
            'memory': {'used': mem.total - mem.available,
                       'total': mem.total},
            'swap': {'used': swap.used,
                     'total': swap.total}
            }
    if len(disk) > 2:
        part = disk[2]
        disk_usg = psutil.disk_usage(part.mountpoint)
        info['disk'] = {'device': part.device,
                        'mount': part.mountpoint,
                        'total': disk_usg.total,
                        'used': disk_usg.used
                        }

    return json.dumps(info)


@mod.route('/shutdown')
def shutdown():
    subprocess.call(["sudo", "halt"])
    return jsonify({'status': 0})


@mod.route('/reboot')
def reboot():
    subprocess.call(["sudo", "reboot"])
    return jsonify({'status': 0})

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Flaskberry{% endblock %}</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href='{{ url_for("static", filename="styles.css") }}'>
    <script type="text/javascript" src="//code.jquery.com/jquery-2.1.3.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/0.9.16/socket.io.min.js"></script>
    <script type="text/javascript" src="//canjs.com/release/2.1.4/can.jquery.js"></script>
    <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    {% block header %}{% endblock %}
</head>

<body>

<div id="wrapper">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand logo" href="/" alt="Flaskberry"></a>

                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    {% for module in config['ENABLED_MODULES'] %}
                    <li><a href='{{ url_for(module+".index")}}'>{{ (module.capitalize()) }}</a></li>
                    {% endfor %}
                    {% for url, link in config['EXTERNAL_LINKS'] %}
                    <li><a href="{{ url }}">{{ link }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" id="main">

        {% for message in get_flashed_messages() %}
        <p class="alert alert-warning">{{ message|safe }}</p>
        {% endfor %}

        <div id="contents">
            {% block contents %}{% endblock %}
        </div>
    </div>
</div>
</body>
</html>

app/templates/disks/disks.html
{% extends "base.html" %}

{% block contents %}
<h2>{{ _('Disks') }}</h2>

<div id="disks" class="row">
{% for disk in disks %}
  <div class="col-md-4"><div class="well">
    {% if disk.mounted %}
        {% if disk.label %}<span class="pull-right">{{ disk.label }}</span>{% endif %}
        <h3>{{ disk.mountpoint }}</h3>
        <div class="row usage">
            <div class="col-md-4" title="disk size">
                {{ disk.usage.total|filesizeformat }}</div>
            <div class="col-md-8">
                <div class="progress">
                {% set used = disk.usage.used|filesizeformat %}
                  <div title="{{ _('%(used)s in use', used = used) }}"
                    class="progress-bar" style="width: {{ disk.usage.percent }}%;">
                    {{ disk.usage.percent }}%</div>
                </div>
            </div>
        </div>
        <a class="btn btn-warning" href="{{ url_for('disks.unmount', uuid=disk.uuid) }}"
            title="{{ _('Unmount %(device)s from %(mountpoint)s', device = disk.dev, mountpoint = disk.mountpoint) }}">
            <span class="glyphicon glyphicon-minus"></span> {{ _('Unmount') }}</a>
    {% else %}
        <h3>{% if disk.label %}{{ disk.label }}{% else %}{{ disk.dev }}{% endif %}</h3>
        <p>{{ _('Type: %(type)s', type = disk.type) }}</p>
        <a class="btn btn-success" href="{{ url_for('disks.mount', uuid=disk.uuid) }}">
            <span class="glyphicon glyphicon-plus"></span> {{ _('Mount') }}</a>
    {% endif %}
  </div></div>
{% endfor %}

</div>

{% endblock %}

app/templates/hello.html
<!DOCTYPE html>
<title>Hello from Flask</title>
{% if name %}
<h1>Hello {{ name }}!</h1>
{% else %}
<h1>Hello World!</h1>
{% endif %}

app/templates/index.html
{% extends "base.html" %}

{% block contents %}
<h1>{{ ('Welcome to Flaskberry') }}</h1>
{% autoescape false %}
<p class="lead">
</p>
{% endautoescape %}
{% endblock %}

app/templates/movies/control.html
{% extends "base.html" %}

{% block header %}
<script type="text/javascript">
var socketNamespace = "{{ url_for('movies.player') }}"
</script>
<script type="text/javascript" src="{{ url_for("static", filename="control.js") }}"></script>
{% endblock %}

{% block contents %}
<div id="movies">
    <h3>{{ _("Remote Control") }}</h3>
    {% include 'movies/player-controls.html' %}

    {% include "movies/list.html" %}
</div>
{% endblock %}

app/templates/movies/list.html
<h3>{{ _('Movies') }}</h3>
<div>
    <div class="btn-group">
    {% for char, movie_group in movies.iteritems() %}
        <a href="#{{char}}" class="btn btn-default">{{char}}</a>
    {% endfor %}
    </div>
    <a href="{{ url_for('movies.refresh') }}"
        title="{{ _('This list is cached for performance reasons, click here to re-scan your library') }}"
        >{{ _('Refresh') }}</a>
</div>

{% for char, movie_group in movies.iteritems() %}
    <h4 id="{{char}}">{{char}}</h4>
    <ul>
    {% for movie in movie_group %}
        <li><a href="{{ movie.path|urlencode }}" class="movie">{{ movie.name }}</a></li>
    {% endfor %}
    </ul>
{% endfor %}

app/templates/movies/movies.html
{% extends "base.html" %}

{% block header %}
<script type="text/javascript" src="{{ url_for("static", filename="movies.js") }}"></script>
<script type="text/javascript">
    var moviesUrl = "{{ config['MOVIES_URL'] }}"
</script>
{% endblock %}

{% block contents %}

<div id="movies">
    <span class="float-right">
        <a class="btn btn-default" href="{{ url_for(".player")}}"><i class="glyphicon glyphicon-film"></i> {{ _("Video Player") }}</a>
        <a class="btn btn-default" href="{{ url_for(".control")}}"><i class="glyphicon glyphicon-phone"></i> {{ _("Remote Control") }}</a>
    </span>

    <div id="video-container">
        <video id="player" width="100%" controls></video>
    </div>

    {% include "movies/list.html" %}

</div>

{% endblock %}

app/templates/movies/player-controls.html
<script type="text/javascript">
var moviesUrl = "{{ config['MOVIES_URL'] }}"
var socketNamespace = "{{ url_for('movies.player') }}"
var lbl = {
    pause: '{{ _("Pause") }}',
    play: '{{ _("Play") }}',
    now_playing: '{{ _("Now Playing:") }}',
    nothing_selcetd: '{{ _("Nothing selected") }}',
    volume: '{{ _("Volume") }}',
    subtitles: '{{ _("Subtitles")}}',
    no_subtitles: '{{ _("No Subtitles")}}',
    subtitles_credits: '{{ _("Subtitles provided by <a href=\"http://www.opensubtitles.org\" target=\"_blank\">OpenSubtitles.org</a>") }}'
}
</script>

{% raw %}

<script id="player-controls" type="text/mustache">
<div class="row">
    <div class="col-xs-4">
        <button-pause></button-pause>
        <select-subtitles></select-subtitles>
        <button-fullscreen></button-fullscreen>
    </div>
    <div class="col-xs-1 col-xs-offset-1">
        <button-mute></button-mute>
    </div>
    <div class="col-xs-6">
        <slider-volume></slider-volume>
    </div>
</div>
<div>
    <b>{{lbl "now_playing" }}</b>
    <span id="now_playing">{{#if fileName}}{{ fileName }}{{ else }}{{lbl "nothing_selected" }}{{/if}}</span><br>
</div>
<div>
    <slider-progress></slider-progress>
</div>
<div>{{{lbl "subtitles_credits"}}}</div>
</script>

<script id="button-pause" type="text/mustache">
<button class="btn btn-default" {{#unless enabled}}disabled="disabled"{{/unless}}>
    <i class="glyphicon glyphicon-{{#if paused}}play{{else}}pause{{/if}}"></i>
    {{#if paused}}{{lbl "play" }}{{else}}{{lbl "pause" }}{{/if}}
</button>
</script>

<script id="button-fullscreen" type="text/mustache">
<button class="btn btn-default {{#unless visible}}hidden{{/unless}}">
    <i class="glyphicon glyphicon-fullscreen"></i>
</button>
</script>

<script id="button-mute" type="text/mustache">
<button class="btn btn-default pull-right">
    <i class="glyphicon glyphicon-volume-{{ iconstate }}"></i>
</button>
</script>

<script id="slider-progress" type="text/mustache">
<div class="progress">
    <div class="progress-bar {{ style }}" role="progressbar" style="width: {{ percent }}%">{{ current }}</div>
    <div class="pull-right" id="duration">{{ total }}</div>
</div>
</script>

<script id="select-subtitles" type="text/mustache">
<div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
        {{lbl "subtitles" }}
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li><a href="#" data-url="none">{{lbl "no_subtitles" }}</a></li>
    {{#each subtitles}}
        <li>
            <a href="#" data-url="{{ url }}" title="{{ name }}">
            <i class="glyphicon glyphicon-{{#isActive}}check{{ else }}unchecked{{/isActive}}"></i>
            {{ language }}
            </a>
        </li>
    {{/each}}
    </ul>
</div>
</script>

{% endraw %}

<div id="video-controls"></div>
<script type="text/javascript" src="{{ url_for("static", filename="player-controls.js") }}"></script>

app/templates/movies/player.html
{% extends "base.html" %}

{% block header %}
<script type="text/javascript">
var socketNamespace = "{{ url_for('movies.player') }}"
var subtitleProxy = "{{ url_for('movies.subtitle_proxy') }}"
</script>
<script type="text/javascript" src="{{ url_for("static", filename="player.js") }}"></script>
{% endblock %}

{% block contents %}
<div id="movies">
    <div id="video-container">
        <video id="player" width="100%"></video>
    </div>
    {% include 'movies/player-controls.html' %}
</div>
{% endblock %}

app/templates/system/system.html
{% extends "base.html" %}

{% block header %}
<script type="text/javascript">
    var refreshTarget = "#info"
</script>
<script type="text/javascript" src="{{ url_for('static', filename='refresh.js') }}"></script>
{% endblock %}

{% block contents %}
<h2>System</h2>
<p>
    <a class="btn btn-danger btn-lg" href="{{ url_for('system.shutdown') }}">
        <span class="glyphicon glyphicon-off"></span>
        Shutdown
    </a>
    <a class="btn btn-danger btn-lg" href="{{ url_for('system.reboot') }}">
        <span class="glyphicon glyphicon-refresh"></span>
        Reboot
    </a>
</p>
<h3>System Information</h3>
<p id="info">
    Uptime: {{uptime}}<br>
    <span title="{{ ('1 min, 5 min, 15 min') }}">
        {% set loads = load|join(", ") %}
        Load Average: {{loads}}
    </span>
    <br>
    CPU Temp:{{temp}}
    <br>
    {% set recv, sent = (net.bytes_recv|filesizeformat, net.bytes_sent|filesizeformat) %}
    Network: {{sent}} sent, {{recv}} received
    <br>
    {% set used, total = ( (memory.total - memory.available)|filesizeformat, memory.total|filesizeformat) %}
    Memory: {{used}} of {{total}} used {{memory.percent}}%<br>
    {% set used, total = ( (swap.total - swap.free)|filesizeformat, swap.total|filesizeformat ) %}
    Swap: {{used}} of {{total}} used {{swap.percent}}%<br>
</p>
{% endblock %}

templates/hello.html
<!DOCTYPE html>
<title>Hello from Flask</title>
{% if name %}
<h1>Hello {{ name }}!</h1>
{% else %}
<h1>Hello World!</h1>
{% endif %}

templates/upload.html
<!DOCTYPE html>
<html lang="en">
<title>Upload new File</title>

<h1>Upload new File</h1>

<form action="" method=post enctype=multipart/form-data>
    <input type=file name=file>
    <input type=submit value=Upload>
</form>
</html>